# Generated by Django 5.1.7 on 2025-03-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, choices=[('BE CE', 'BE Computer'), ('BE Civil', 'BE Civil'), ('BE Electronics and Communication', 'BE Electronics and Communication'), ('BE IT', 'BE IT'), ('B. Architecture', 'B. Architecture'), ('BCA', 'Bachelor of Computer Application'), ('BBA', 'Bachelor of Business Adminstration')], max_length=50, null=True),
        ),
    ]
